/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as AdminStatSchemasRouteImport } from './routes/admin/stat-schemas'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminRoomProgramsRouteImport } from './routes/admin/room-programs'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatSchemasRoute = AdminStatSchemasRouteImport.update({
  id: '/admin/stat-schemas',
  path: '/admin/stat-schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomProgramsRoute = AdminRoomProgramsRouteImport.update({
  id: '/admin/room-programs',
  path: '/admin/room-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/room-programs': typeof AdminRoomProgramsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/stat-schemas': typeof AdminStatSchemasRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/room-programs': typeof AdminRoomProgramsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/stat-schemas': typeof AdminStatSchemasRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/room-programs': typeof AdminRoomProgramsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/stat-schemas': typeof AdminStatSchemasRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/login'
    | '/admin/accounts'
    | '/admin/jobs'
    | '/admin/roles'
    | '/admin/room-programs'
    | '/admin/rooms'
    | '/admin/stat-schemas'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/account/'
    | '/admin/'
    | '/matches/'
    | '/players/'
    | '/rooms/'
    | '/stats/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/login'
    | '/admin/accounts'
    | '/admin/jobs'
    | '/admin/roles'
    | '/admin/room-programs'
    | '/admin/rooms'
    | '/admin/stat-schemas'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/account'
    | '/admin'
    | '/matches'
    | '/players'
    | '/rooms'
    | '/stats'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account/login'
    | '/admin/accounts'
    | '/admin/jobs'
    | '/admin/roles'
    | '/admin/room-programs'
    | '/admin/rooms'
    | '/admin/stat-schemas'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/account/'
    | '/admin/'
    | '/matches/'
    | '/players/'
    | '/rooms/'
    | '/stats/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminRoomProgramsRoute: typeof AdminRoomProgramsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminStatSchemasRoute: typeof AdminStatSchemasRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stat-schemas': {
      id: '/admin/stat-schemas'
      path: '/admin/stat-schemas'
      fullPath: '/admin/stat-schemas'
      preLoaderRoute: typeof AdminStatSchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/room-programs': {
      id: '/admin/room-programs'
      path: '/admin/room-programs'
      fullPath: '/admin/room-programs'
      preLoaderRoute: typeof AdminRoomProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountLoginRoute: AccountLoginRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminRoomProgramsRoute: AdminRoomProgramsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminStatSchemasRoute: AdminStatSchemasRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
